- hosts: lamp-web
  become: true

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm

  tasks:
    - name: Remove file default homepage (delete file)
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy template file to test apache php server
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php
