- hosts: lamp-www
  become: true

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.firewall
    - geerlingguy.php-mysql


  tasks:
    - name: Ensure php-cli is installed for ubuntu
      apt:
        name: libapache2-mod-php 
        state: present

    - name: Remove file default homepage (delete file)
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy template file to test apache php server
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php
