- hosts: lamp-web
  become: true

  vars:
    php_enable_php_fpm: true
    apache_vhosts:
      - servername: "www.example.com"
        documentroot: "/var/www/html"
        extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/html"

  collections:
    - geerlingguy.php_roles

  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm

  tasks:
    - name: Remove file default homepage (delete file)
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy template file to test apache php server
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php
