---
- src: geerlingguy.firewall
- src: geerlingguy.repo-epel
- src: geerlingguy.varnish
- src: geerlingguy.apache
- src: geerlingguy.php
- src: geerlingguy.php-mysql
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.php-memcached
- src: geerlingguy.mysql
- src: geerlingguy.memcached
- src: cloudalchemy.prometheus
- src: cloudalchemy.node-exporter
- src: cloudalchemy.grafana
