---
- hosts: lamp-varnish
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.varnish
    - geerlingguy.firewall

  pre_tasks:
      - name: Update the apt cache
        apt: update_cache=yes state=latest

      # - name: Upgrade all packages on servers
      #   apt: upgrade=dist force_apt_get=yes

  tasks:
    - name: Copy Varnish default.vcl.
      template:
        src: "templates/default.vcl.j2"
        dest: "/etc/varnish/default.vcl"
      notify: restart varnish

    - debug: var=hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address']
